name: CI

on:
 workflow_dispatch

env:
  DOCKER_IMAGE: subramsr/flaskimg
  DOCKER_USERNAME: ${{vars.DOCKER_NAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWD}}

jobs:
 code-checkout:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v5.0.0
   - name: List files in workspace
     run: |
      echo "Current directory: $(pwd)"
      ls -al
     
 build:
  needs: code-checkout
  runs-on: ubuntu-latest
  steps:
   - name: Docker Login
     uses: docker/login-action@v3.5.0
     with:
      username: ${{env.DOCKER_USERNAME}}
      password: ${{env.DOCKER_PASSWORD}}
   - name: Checkout
     uses: actions/checkout@v5.0.0
     
   - name: Build docker image
     run: |
      echo "Current directory: $(pwd)"
      ls -al
      docker build -t $DOCKER_IMAGE:${{github.sha}} .
      docker tag $DOCKER_IMAGE:${{github.sha}} $DOCKER_IMAGE:latest
   - name: Push the docker image
     run: |
      docker push $DOCKER_IMAGE:${{github.sha}}
      docker push $DOCKER_IMAGE:latest
   - name: Pull the docker image(latest)
     run: |
      docker pull $DOCKER_IMAGE:latest
   - name: Run container from pulled image
     run: |
      docker run -d -p 5000:5000 $DOCKER_IMAGE:latest
     
 SonarQube:
  needs: code-checkout
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v5.0.0
   - name: Setup Java JDK
     uses: actions/setup-java@v5.0.0
     with:
      distribution: 'microsoft'
      java-version: '17'
   - name: Cache SonarQube packages
     uses: actions/cache@v4
     with:
      path: ~/.sonar/cache
      key: ${{runner.os}}-sonar
      restore-keys: ${{runner-os}}-sonar
   - name: Run SonarQube Analysis
     uses: SonarSource/sonarcloud-github-action@master
     with:
      args: >
       -Dsonar.projectKey = my_project_key
       -Dsonar.organization = my_org
       -Dsonar.host.url = ${{env.SONAR_HOST_URL}}
       -Dsonar.login = ${{env.SONAR_TOKEN}}
  
 

