name: CI

on:
 workflow_dispatch

env:
  DOCKER_IMAGE: subramsr/flaskimg
  DOCKER_USERNAME: ${{vars.DOCKER_NAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWD}}

jobs:
 code-checkout:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v5.0.0
   - name: List files in workspace
     run: |
      echo "Current directory: $(pwd)"
      ls -al
     
 build:
  needs: code-checkout
  runs-on: ubuntu-latest
  steps:
   - name: Docker Login
     uses: docker/login-action@v3.5.0
     with:
      username: ${{env.DOCKER_USERNAME}}
      password: ${{env.DOCKER_PASSWORD}}
   - name: Checkout
     uses: actions/checkout@v5.0.0
     
   - name: Build docker image
     run: |
      echo "Current directory: $(pwd)"
      ls -al
      docker build -t $DOCKER_IMAGE:${{github.sha}} .
      docker tag $DOCKER_IMAGE:${{github.sha}} $DOCKER_IMAGE:latest
     
     
  
 

