name: CI

on:
 workflow_dispatch

env:
  DOCKER_IMAGE: subramsr/python_image
  DOCKER_USERNAME: ${{vars.DOCKER_NAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWD}}

jobs:
 code-checkout:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v5.0.0
 build:
  needs: code-checkout
  runs-on: ubuntu-latest
  steps:
   - name: Docker Login
     uses: docker/login-action@v3.5.0
     with:
      username: ${{env.DOCKER_USERNAME}}
      password: ${{env.DOCKER_PASSWORD}}
   - name: Build Docker image
     run: |
      docker build -t ${{env.DOCKER_IMAGE}}:${{github.sha}}
      docker tag $DOCKER_IMAGE:${{github.sha}} $DOCKER_IMAGE:latest
     
     
  
 

