name: CI

on:
 workflow_dispatch

 env:
  DOCKER_IMAGE: subramsr/python_image
  DOCKER_USERNAME: ${{vars.DOCKER_NAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWD}}

jobs:
 code-checkout:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v5.0.0
